name: build
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: cv
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv
          compiler: xelatex
          working_directory: .

      - name: move
        run: mkdir -p github_artifacts && mv cv.pdf ./github_artifacts/

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./github_artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts

      - name: move
        run: |
          mkdir -p github_deploy
          find github_artifacts -name "cv.pdf" -exec cp {} github_deploy/ \;
          cp index.html github_deploy/
          if [ -f CNAME ]; then cp CNAME github_deploy/; fi
          touch github_deploy/.nojekyll

      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: false
